import * as React from "react"
import { toast } from "sonner"
import { FileTree, useFileTree } from "@pierre/trees/react"
import {
  IconAlertTriangle,
  IconCopy,
  IconDownload,
  IconTextWrap,
} from "@tabler/icons-react"

import { AGENTS, ARTIFACT_TYPES } from "@/lib/domain"
import { formatBytes } from "@/lib/format"
import type { Artifact } from "@/lib/types"
import { cn } from "@/lib/utils"
import {
  artifactBody,
  artifactByPath,
  baseName,
  buildArtifactPaths,
  isPreviewOnly,
} from "@/features/runs/lib/artifact-tree"
import { useHighlighted } from "@/features/runs/lib/highlighter"
import { AgentGlyph } from "@/features/migrations/components/agent"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogTitle,
} from "@/components/ui/dialog"

/** Maps Pierre's shadow-DOM theme variables onto the app's design tokens. */
const TREE_THEME = {
  "--trees-fg-override": "var(--foreground)",
  "--trees-fg-muted-override": "var(--muted-foreground)",
  "--trees-bg-override": "transparent",
  "--trees-bg-muted-override": "var(--muted)",
  "--trees-accent-override": "var(--primary)",
  "--trees-border-color-override": "var(--border)",
  "--trees-selected-bg-override": "var(--accent)",
  "--trees-selected-fg-override": "var(--accent-foreground)",
  "--trees-selected-focused-border-color-override": "var(--ring)",
  "--trees-focus-ring-color-override": "var(--ring)",
} as React.CSSProperties

function CodePane({ artifact }: { artifact: Artifact }) {
  const meta = ARTIFACT_TYPES[artifact.type]
  const body = artifactBody(artifact)
  const html = useHighlighted(body, meta.language)
  const [wrap, setWrap] = React.useState(false)
  const previewOnly = isPreviewOnly(artifact)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(body)
      toast.success("Copied to clipboard")
    } catch {
      toast.error("Couldn't copy")
    }
  }

  const download = () => {
    const blob = new Blob([body], { type: "text/plain;charset=utf-8" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = baseName(artifact.fileName)
    a.click()
    URL.revokeObjectURL(url)
    toast(`Downloaded ${baseName(artifact.fileName)}`)
  }

  return (
    <div className="flex min-w-0 flex-1 flex-col">
      <header className="flex items-center gap-2.5 border-b border-border py-2.5 pr-11 pl-3.5">
        <meta.icon className="size-4 shrink-0 text-muted-foreground" />
        <div className="flex min-w-0 flex-1 flex-col">
          <h2 className="truncate font-mono text-[13px] font-medium">
            {artifact.fileName}
          </h2>
          <span className="flex items-center gap-1.5 text-[10px] text-muted-foreground">
            <AgentGlyph agent={artifact.createdBy} size="sm" />
            <span style={{ color: AGENTS[artifact.createdBy].color }}>
              {AGENTS[artifact.createdBy].name}
            </span>
            <span aria-hidden>·</span>
            <span className="tabular">{formatBytes(artifact.sizeBytes)}</span>
          </span>
        </div>
        <Badge variant="outline" className="font-mono text-[10px] tracking-wide">
          {meta.language.toUpperCase()}
        </Badge>
        <Button
          size="icon-xs"
          variant="ghost"
          aria-pressed={wrap}
          aria-label="Toggle line wrap"
          className={cn(wrap && "bg-muted text-foreground")}
          onClick={() => setWrap((w) => !w)}
        >
          <IconTextWrap />
        </Button>
        <Button
          size="icon-xs"
          variant="ghost"
          aria-label="Copy code"
          onClick={copy}
        >
          <IconCopy />
        </Button>
        <Button
          size="icon-xs"
          variant="ghost"
          aria-label={`Download ${baseName(artifact.fileName)}`}
          onClick={download}
        >
          <IconDownload />
        </Button>
      </header>

      {previewOnly && (
        <p className="flex items-center gap-1.5 border-b border-warning/30 bg-warning/10 px-3.5 py-1.5 text-[11px] text-warning">
          <IconAlertTriangle className="size-3 shrink-0" />
          Showing preview. The full file loads here once the run uploads it.
        </p>
      )}

      <div className="min-h-0 flex-1 overflow-auto">
        <span className="sr-only">
          {meta.label} generated by {AGENTS[artifact.createdBy].name}
        </span>
        {html ? (
          <div
            className="code-surface"
            data-wrap={wrap}
            dangerouslySetInnerHTML={{ __html: html }}
          />
        ) : (
          <div className="flex flex-col gap-1.5 p-4">
            {Array.from({ length: 8 }).map((_, i) => (
              <div
                key={i}
                className="h-3 animate-pulse rounded-none bg-muted"
                style={{ width: `${40 + ((i * 37) % 55)}%` }}
              />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

export function CodeViewerBody({
  artifacts,
  initialPath,
}: {
  artifacts: Artifact[]
  initialPath?: string
}) {
  const paths = React.useMemo(() => buildArtifactPaths(artifacts), [artifacts])
  const byPath = React.useMemo(() => artifactByPath(artifacts), [artifacts])
  const firstPath =
    initialPath && byPath.has(initialPath) ? initialPath : paths[0]
  const [activePath, setActivePath] = React.useState(firstPath)

  // Drive selection through the model's own callback rather than the
  // `useFileTreeSelection` hook: that hook passes a fresh selector every render,
  // which busts its snapshot cache and loops `useSyncExternalStore`.
  const { model } = useFileTree({
    paths,
    initialExpansion: "open",
    initialSelectedPaths: firstPath ? [firstPath] : [],
    stickyFolders: true,
    onSelectionChange: (selected) => {
      const hit = selected.find((p) => byPath.has(p))
      if (hit) setActivePath(hit)
    },
  })

  const artifact = activePath ? byPath.get(activePath) : undefined

  return (
    <div className="flex h-full min-h-0">
      <div className="flex w-60 shrink-0 flex-col border-r border-border bg-muted/30">
        <div className="border-b border-border px-3 py-2.5 text-[10px] font-semibold tracking-wide text-muted-foreground uppercase">
          Files
        </div>
        <div className="min-h-0 flex-1 overflow-hidden p-1.5" style={TREE_THEME}>
          <FileTree model={model} className="size-full text-[13px]" />
        </div>
      </div>
      {artifact ? (
        <CodePane key={artifact.id} artifact={artifact} />
      ) : (
        <div className="flex flex-1 items-center justify-center text-xs text-muted-foreground">
          Select a file to view its code.
        </div>
      )}
    </div>
  )
}

export default function CodeViewerDialog({
  artifacts,
  open,
  onOpenChange,
  initialPath,
}: {
  artifacts: Artifact[]
  open: boolean
  onOpenChange: (open: boolean) => void
  initialPath?: string
}) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="flex h-[85vh] max-w-[min(1100px,95vw)] flex-col gap-0 overflow-hidden p-0">
        <DialogTitle className="sr-only">Generated artifacts</DialogTitle>
        <DialogDescription className="sr-only">
          Browse generated files for this run.
        </DialogDescription>
        {open && (
          <CodeViewerBody artifacts={artifacts} initialPath={initialPath} />
        )}
      </DialogContent>
    </Dialog>
  )
}
