package worker

import (
	"context"
	"fmt"

	"github.com/ferry/backend/internal/band"
	"github.com/ferry/backend/internal/github"
)

// createPR opens a real GitHub pull request with the run's accumulated
// generated files, using the run creator's OAuth token. Returns the PR URL.
func (w *Worker) createPR(ctx context.Context, rc band.RunCtx) (string, error) {
	files := w.loadFiles(ctx, rc.Run)
	if len(files) == 0 {
		return "", fmt.Errorf("no generated files to commit")
	}
	owner, name, ok := splitRepo(rc.Repo)
	if !ok {
		return "", fmt.Errorf("invalid repo %q", rc.Repo)
	}
	token := w.source.WriteToken(ctx, rc.User)
	if token == "" {
		return "", fmt.Errorf("no GitHub write token available (set GITHUB_PAT with repo scope, or re-login with repo scope)")
	}

	branch := "ferry-migration-" + shortID(rc.Run)
	title := fmt.Sprintf("Ferry: migrate %s from %s to %s", rc.Repo, rc.Src, rc.Tgt)
	body := fmt.Sprintf("Automated migration generated by the Ferry agent band (%s → %s).", rc.Src, rc.Tgt)

	gh := github.NewClient(token)
	return gh.OpenPullRequest(ctx, owner, name, rc.Branch, branch, title, body, files)
}

func shortID(s string) string {
	if len(s) > 8 {
		return s[:8]
	}
	return s
}
