package worker

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"strings"

	"github.com/ferry/backend/internal/band"
	"github.com/ferry/backend/internal/github"
)

type pullRequestResult struct {
	URL          string `json:"url"`
	Number       int    `json:"number"`
	Title        string `json:"title"`
	SourceBranch string `json:"sourceBranch"`
	TargetBranch string `json:"targetBranch"`
}

func (r pullRequestResult) artifactBlock() (string, error) {
	raw, err := json.Marshal(r)
	if err != nil {
		return "", err
	}
	return band.MarshalArtifact(band.Artifact{Kind: "pull_request", Status: "open", Body: string(raw)}), nil
}

// createPR opens a real GitHub pull request with the run's accumulated
// generated files, using the run creator's OAuth token.
func (w *Worker) createPR(ctx context.Context, rc band.RunCtx) (pullRequestResult, error) {
	files := w.loadFiles(ctx, rc.Run)
	if len(files) == 0 {
		return pullRequestResult{}, fmt.Errorf("no generated files to commit")
	}
	owner, name, ok := splitRepo(rc.Repo)
	if !ok {
		return pullRequestResult{}, fmt.Errorf("invalid repo %q", rc.Repo)
	}
	tokens := w.source.WriteTokens(ctx, rc.User, owner, name, rc.IsGuest)
	if len(tokens) == 0 {
		return pullRequestResult{}, fmt.Errorf("no GitHub write token available (install the Ferry GitHub App on this repo, or set GITHUB_PAT with repo scope)")
	}

	branch := migrationBranch(rc.Run)
	title := fmt.Sprintf("Ferry: migrate %s from %s to %s", rc.Repo, rc.Src, rc.Tgt)
	body := fmt.Sprintf("Automated migration generated by the Ferry agent band (%s → %s).", rc.Src, rc.Tgt)

	// Try each credential in turn. A permission failure (e.g. the GitHub App
	// login token can't write this repo) falls through to the next token (the
	// PAT); any other error is terminal and won't be fixed by a different token.
	var lastErr error
	for i, token := range tokens {
		url, number, err := github.NewClient(token).OpenPullRequest(ctx, owner, name, rc.Branch, branch, title, body, files)
		if err == nil {
			return pullRequestResult{
				URL:          url,
				Number:       number,
				Title:        title,
				SourceBranch: branch,
				TargetBranch: rc.Branch,
			}, nil
		}
		lastErr = err
		if !isPermissionError(err) {
			break
		}
		if i < len(tokens)-1 {
			log.Printf("[%s] PR credential %d/%d rejected (no write access), trying fallback: %v", w.info.Key, i+1, len(tokens), err)
		}
	}
	return pullRequestResult{}, annotateTokenError(lastErr)
}

// isPermissionError reports whether a GitHub error is an auth/permission failure
// that a different credential might resolve (rather than a bad-request, etc.).
func isPermissionError(err error) bool {
	low := strings.ToLower(err.Error())
	return strings.Contains(low, "403") ||
		strings.Contains(low, "401") ||
		strings.Contains(low, "not accessible") ||
		strings.Contains(low, "forbidden")
}

// annotateTokenError turns GitHub's opaque 403 ("Resource not accessible by
// integration") into an actionable message. That status means the login token
// can't write to the repo — for a GitHub App, the user-to-server token only
// writes when the App has Contents/Pull-request write permission AND is
// installed on the target repo (GitHub Apps ignore OAuth scopes).
func annotateTokenError(err error) error {
	msg := err.Error()
	low := strings.ToLower(msg)
	if strings.Contains(low, "403") || strings.Contains(low, "not accessible") || strings.Contains(low, "forbidden") {
		return fmt.Errorf("%s — no available GitHub credential can write to this repo. "+
			"Quick unblock: set GITHUB_PAT to a classic token with the `repo` scope (it's used automatically as a fallback). "+
			"To use the GitHub App login instead: set the App's 'Contents' and 'Pull requests' permissions to Read/write, "+
			"install the App on this repository (approve the permission update), then log out and back in to refresh the token", msg)
	}
	return err
}

func migrationBranch(runID string) string {
	return "ferry-migration-" + runID
}
