// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_messages.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentMessages = `-- name: CountAgentMessages :one
SELECT COUNT(*) FROM agent_messages
WHERE company_id = $1 AND migration_run_id = $2
`

func (q *Queries) CountAgentMessages(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentMessages, companyID, migrationRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAgentMessage = `-- name: CreateAgentMessage :one
INSERT INTO agent_messages (company_id, project_id, migration_run_id, band_room_id, band_message_id, agent_name, message_type, phase, summary, payload, confidence, requires_action, target_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, company_id, project_id, migration_run_id, band_room_id, band_message_id, agent_name, message_type, phase, summary, payload, confidence, requires_action, target_agent, created_at, updated_at
`

type CreateAgentMessageParams struct {
	CompanyID      uuid.UUID      `json:"company_id"`
	ProjectID      uuid.UUID      `json:"project_id"`
	MigrationRunID uuid.UUID      `json:"migration_run_id"`
	BandRoomID     string         `json:"band_room_id"`
	BandMessageID  *string        `json:"band_message_id"`
	AgentName      string         `json:"agent_name"`
	MessageType    MessageType    `json:"message_type"`
	Phase          MigrationPhase `json:"phase"`
	Summary        string         `json:"summary"`
	Payload        []byte         `json:"payload"`
	Confidence     pgtype.Numeric `json:"confidence"`
	RequiresAction *bool          `json:"requires_action"`
	TargetAgent    *string        `json:"target_agent"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) (AgentMessage, error) {
	row := q.db.QueryRow(ctx, createAgentMessage,
		arg.CompanyID,
		arg.ProjectID,
		arg.MigrationRunID,
		arg.BandRoomID,
		arg.BandMessageID,
		arg.AgentName,
		arg.MessageType,
		arg.Phase,
		arg.Summary,
		arg.Payload,
		arg.Confidence,
		arg.RequiresAction,
		arg.TargetAgent,
	)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.BandMessageID,
		&i.AgentName,
		&i.MessageType,
		&i.Phase,
		&i.Summary,
		&i.Payload,
		&i.Confidence,
		&i.RequiresAction,
		&i.TargetAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentMessage = `-- name: GetAgentMessage :one
SELECT id, company_id, project_id, migration_run_id, band_room_id, band_message_id, agent_name, message_type, phase, summary, payload, confidence, requires_action, target_agent, created_at, updated_at FROM agent_messages
WHERE company_id = $1 AND id = $2
`

func (q *Queries) GetAgentMessage(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (AgentMessage, error) {
	row := q.db.QueryRow(ctx, getAgentMessage, companyID, iD)
	var i AgentMessage
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.BandMessageID,
		&i.AgentName,
		&i.MessageType,
		&i.Phase,
		&i.Summary,
		&i.Payload,
		&i.Confidence,
		&i.RequiresAction,
		&i.TargetAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentTimeline = `-- name: GetAgentTimeline :many
SELECT 
    id,
    agent_name,
    message_type,
    phase,
    summary,
    target_agent,
    confidence,
    requires_action,
    created_at
FROM agent_messages
WHERE company_id = $1 AND migration_run_id = $2
ORDER BY created_at ASC
`

type GetAgentTimelineRow struct {
	ID             uuid.UUID          `json:"id"`
	AgentName      string             `json:"agent_name"`
	MessageType    MessageType        `json:"message_type"`
	Phase          MigrationPhase     `json:"phase"`
	Summary        string             `json:"summary"`
	TargetAgent    *string            `json:"target_agent"`
	Confidence     pgtype.Numeric     `json:"confidence"`
	RequiresAction *bool              `json:"requires_action"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAgentTimeline(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID) ([]GetAgentTimelineRow, error) {
	rows, err := q.db.Query(ctx, getAgentTimeline, companyID, migrationRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAgentTimelineRow{}
	for rows.Next() {
		var i GetAgentTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.AgentName,
			&i.MessageType,
			&i.Phase,
			&i.Summary,
			&i.TargetAgent,
			&i.Confidence,
			&i.RequiresAction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT id, company_id, project_id, migration_run_id, band_room_id, band_message_id, agent_name, message_type, phase, summary, payload, confidence, requires_action, target_agent, created_at, updated_at FROM agent_messages
WHERE company_id = $1 AND migration_run_id = $2
ORDER BY created_at ASC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListAgentMessages(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID, limit int32, offset int32) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listAgentMessages,
		companyID,
		migrationRunID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ProjectID,
			&i.MigrationRunID,
			&i.BandRoomID,
			&i.BandMessageID,
			&i.AgentName,
			&i.MessageType,
			&i.Phase,
			&i.Summary,
			&i.Payload,
			&i.Confidence,
			&i.RequiresAction,
			&i.TargetAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessagesByPhase = `-- name: ListAgentMessagesByPhase :many
SELECT id, company_id, project_id, migration_run_id, band_room_id, band_message_id, agent_name, message_type, phase, summary, payload, confidence, requires_action, target_agent, created_at, updated_at FROM agent_messages
WHERE company_id = $1 AND migration_run_id = $2 AND phase = $3
ORDER BY created_at ASC
`

func (q *Queries) ListAgentMessagesByPhase(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID, phase MigrationPhase) ([]AgentMessage, error) {
	rows, err := q.db.Query(ctx, listAgentMessagesByPhase, companyID, migrationRunID, phase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentMessage{}
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ProjectID,
			&i.MigrationRunID,
			&i.BandRoomID,
			&i.BandMessageID,
			&i.AgentName,
			&i.MessageType,
			&i.Phase,
			&i.Summary,
			&i.Payload,
			&i.Confidence,
			&i.RequiresAction,
			&i.TargetAgent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
