// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (company_id, user_id, action, resource_type, resource_id, details, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, created_at
`

func (q *Queries) CreateAuditLog(ctx context.Context, companyID pgtype.UUID, userID pgtype.UUID, action AuditAction, resourceType *string, resourceID pgtype.UUID, details []byte, ipAddress *netip.Addr, userAgent *string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		companyID,
		userID,
		action,
		resourceType,
		resourceID,
		details,
		ipAddress,
		userAgent,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Details,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, company_id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, created_at FROM audit_logs
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListAuditLogs(ctx context.Context, companyID pgtype.UUID, limit int32, offset int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, companyID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, company_id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, created_at FROM audit_logs
WHERE company_id = $1 AND action = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListAuditLogsByAction(ctx context.Context, companyID pgtype.UUID, action AuditAction, limit int32, offset int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAction,
		companyID,
		action,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByResource = `-- name: ListAuditLogsByResource :many
SELECT id, company_id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, created_at FROM audit_logs
WHERE company_id = $1 AND resource_type = $2 AND resource_id = $3
ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogsByResource(ctx context.Context, companyID pgtype.UUID, resourceType *string, resourceID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByResource, companyID, resourceType, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, company_id, user_id, action, resource_type, resource_id, details, ip_address, user_agent, created_at FROM audit_logs
WHERE company_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListAuditLogsByUser(ctx context.Context, companyID pgtype.UUID, userID pgtype.UUID, limit int32, offset int32) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser,
		companyID,
		userID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Details,
			&i.IpAddress,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
