// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: band_rooms.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBandRoom = `-- name: CreateBandRoom :one
INSERT INTO band_rooms (company_id, migration_run_id, band_room_id, room_name, room_description, room_metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, migration_run_id, band_room_id, room_name, room_description, room_metadata, created_at, updated_at
`

func (q *Queries) CreateBandRoom(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID, bandRoomID string, roomName string, roomDescription *string, roomMetadata []byte) (BandRoom, error) {
	row := q.db.QueryRow(ctx, createBandRoom,
		companyID,
		migrationRunID,
		bandRoomID,
		roomName,
		roomDescription,
		roomMetadata,
	)
	var i BandRoom
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.RoomName,
		&i.RoomDescription,
		&i.RoomMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBandRoom = `-- name: GetBandRoom :one
SELECT id, company_id, migration_run_id, band_room_id, room_name, room_description, room_metadata, created_at, updated_at FROM band_rooms
WHERE company_id = $1 AND id = $2
`

func (q *Queries) GetBandRoom(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (BandRoom, error) {
	row := q.db.QueryRow(ctx, getBandRoom, companyID, iD)
	var i BandRoom
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.RoomName,
		&i.RoomDescription,
		&i.RoomMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBandRoomByBandID = `-- name: GetBandRoomByBandID :one
SELECT id, company_id, migration_run_id, band_room_id, room_name, room_description, room_metadata, created_at, updated_at FROM band_rooms
WHERE band_room_id = $1
`

func (q *Queries) GetBandRoomByBandID(ctx context.Context, bandRoomID string) (BandRoom, error) {
	row := q.db.QueryRow(ctx, getBandRoomByBandID, bandRoomID)
	var i BandRoom
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.RoomName,
		&i.RoomDescription,
		&i.RoomMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBandRoomByRunID = `-- name: GetBandRoomByRunID :one
SELECT id, company_id, migration_run_id, band_room_id, room_name, room_description, room_metadata, created_at, updated_at FROM band_rooms
WHERE company_id = $1 AND migration_run_id = $2
`

func (q *Queries) GetBandRoomByRunID(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID) (BandRoom, error) {
	row := q.db.QueryRow(ctx, getBandRoomByRunID, companyID, migrationRunID)
	var i BandRoom
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.RoomName,
		&i.RoomDescription,
		&i.RoomMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBandRoomMetadata = `-- name: UpdateBandRoomMetadata :one
UPDATE band_rooms
SET room_metadata = $3
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, migration_run_id, band_room_id, room_name, room_description, room_metadata, created_at, updated_at
`

func (q *Queries) UpdateBandRoomMetadata(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, roomMetadata []byte) (BandRoom, error) {
	row := q.db.QueryRow(ctx, updateBandRoomMetadata, companyID, iD, roomMetadata)
	var i BandRoom
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.MigrationRunID,
		&i.BandRoomID,
		&i.RoomName,
		&i.RoomDescription,
		&i.RoomMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
