// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name, slug, subscription_tier, max_projects, max_users, settings)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, slug, subscription_tier, max_projects, max_users, settings, created_at, updated_at, deleted_at
`

func (q *Queries) CreateCompany(ctx context.Context, name string, slug string, subscriptionTier *string, maxProjects *int32, maxUsers *int32, settings []byte) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany,
		name,
		slug,
		subscriptionTier,
		maxProjects,
		maxUsers,
		settings,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SubscriptionTier,
		&i.MaxProjects,
		&i.MaxUsers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCompany = `-- name: DeleteCompany :exec
UPDATE companies
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCompany(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompany, id)
	return err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, name, slug, subscription_tier, max_projects, max_users, settings, created_at, updated_at, deleted_at FROM companies
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SubscriptionTier,
		&i.MaxProjects,
		&i.MaxUsers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCompanyBySlug = `-- name: GetCompanyBySlug :one
SELECT id, name, slug, subscription_tier, max_projects, max_users, settings, created_at, updated_at, deleted_at FROM companies
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCompanyBySlug(ctx context.Context, slug string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyBySlug, slug)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SubscriptionTier,
		&i.MaxProjects,
		&i.MaxUsers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, slug, subscription_tier, max_projects, max_users, settings, created_at, updated_at, deleted_at FROM companies
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

func (q *Queries) ListCompanies(ctx context.Context, limit int32, offset int32) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Company{}
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SubscriptionTier,
			&i.MaxProjects,
			&i.MaxUsers,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE companies
SET name = $2, settings = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, subscription_tier, max_projects, max_users, settings, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateCompany(ctx context.Context, iD uuid.UUID, name string, settings []byte) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompany, iD, name, settings)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SubscriptionTier,
		&i.MaxProjects,
		&i.MaxUsers,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
