// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE memberships
SET accepted_at = NOW()
WHERE company_id = $1 AND user_id = $2
RETURNING id, company_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at
`

func (q *Queries) AcceptInvitation(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, companyID, userID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCompanyMembers = `-- name: CountCompanyMembers :one
SELECT COUNT(*) FROM memberships
WHERE company_id = $1
`

func (q *Queries) CountCompanyMembers(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompanyMembers, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMembership = `-- name: CreateMembership :one
INSERT INTO memberships (company_id, user_id, role, invited_by, invited_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at
`

func (q *Queries) CreateMembership(ctx context.Context, companyID uuid.UUID, userID uuid.UUID, role MembershipRole, invitedBy pgtype.UUID, invitedAt pgtype.Timestamptz) (Membership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		companyID,
		userID,
		role,
		invitedBy,
		invitedAt,
	)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships
WHERE company_id = $1 AND user_id = $2
`

func (q *Queries) DeleteMembership(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMembership, companyID, userID)
	return err
}

const getCompanyMembers = `-- name: GetCompanyMembers :many
SELECT m.id, m.company_id, m.user_id, m.role, m.invited_by, m.invited_at, m.accepted_at, m.created_at, m.updated_at, u.email, u.full_name, u.avatar_url
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.company_id = $1 AND u.deleted_at IS NULL
ORDER BY m.created_at ASC
`

type GetCompanyMembersRow struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       MembershipRole     `json:"role"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	AvatarUrl  *string            `json:"avatar_url"`
}

func (q *Queries) GetCompanyMembers(ctx context.Context, companyID uuid.UUID) ([]GetCompanyMembersRow, error) {
	rows, err := q.db.Query(ctx, getCompanyMembers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompanyMembersRow{}
	for rows.Next() {
		var i GetCompanyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMembership = `-- name: GetMembership :one
SELECT id, company_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at FROM memberships
WHERE company_id = $1 AND user_id = $2
`

func (q *Queries) GetMembership(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) (Membership, error) {
	row := q.db.QueryRow(ctx, getMembership, companyID, userID)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserMemberships = `-- name: GetUserMemberships :many
SELECT m.id, m.company_id, m.user_id, m.role, m.invited_by, m.invited_at, m.accepted_at, m.created_at, m.updated_at, c.name as company_name, c.slug as company_slug
FROM memberships m
JOIN companies c ON c.id = m.company_id
WHERE m.user_id = $1 AND c.deleted_at IS NULL
ORDER BY m.created_at DESC
`

type GetUserMembershipsRow struct {
	ID          uuid.UUID          `json:"id"`
	CompanyID   uuid.UUID          `json:"company_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        MembershipRole     `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt  pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CompanyName string             `json:"company_name"`
	CompanySlug string             `json:"company_slug"`
}

func (q *Queries) GetUserMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserMembershipsRow, error) {
	rows, err := q.db.Query(ctx, getUserMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserMembershipsRow{}
	for rows.Next() {
		var i GetUserMembershipsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.InvitedAt,
			&i.AcceptedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
			&i.CompanySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE memberships
SET role = $3
WHERE company_id = $1 AND user_id = $2
RETURNING id, company_id, user_id, role, invited_by, invited_at, accepted_at, created_at, updated_at
`

func (q *Queries) UpdateMembershipRole(ctx context.Context, companyID uuid.UUID, userID uuid.UUID, role MembershipRole) (Membership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, companyID, userID, role)
	var i Membership
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.InvitedAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
