// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: migration_runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const completeMigrationRun = `-- name: CompleteMigrationRun :one
UPDATE migration_runs
SET status = $3, completed_at = NOW()
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, error_message, started_at, completed_at, created_by, created_at, updated_at
`

func (q *Queries) CompleteMigrationRun(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, status *MigrationStatus) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, completeMigrationRun, companyID, iD, status)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.RunNumber,
		&i.Status,
		&i.BandRoomID,
		&i.SourceCommitSha,
		&i.TargetBranch,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countMigrationRuns = `-- name: CountMigrationRuns :one
SELECT COUNT(*) FROM migration_runs
WHERE company_id = $1 AND project_id = $2
`

func (q *Queries) CountMigrationRuns(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMigrationRuns, companyID, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMigrationRun = `-- name: CreateMigrationRun :one
INSERT INTO migration_runs (company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, error_message, started_at, completed_at, created_by, created_at, updated_at
`

func (q *Queries) CreateMigrationRun(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID, runNumber int32, status *MigrationStatus, bandRoomID *string, sourceCommitSha *string, targetBranch *string, createdBy uuid.UUID) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, createMigrationRun,
		companyID,
		projectID,
		runNumber,
		status,
		bandRoomID,
		sourceCommitSha,
		targetBranch,
		createdBy,
	)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.RunNumber,
		&i.Status,
		&i.BandRoomID,
		&i.SourceCommitSha,
		&i.TargetBranch,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMigrationRun = `-- name: GetMigrationRun :one
SELECT id, company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, error_message, started_at, completed_at, created_by, created_at, updated_at FROM migration_runs
WHERE company_id = $1 AND id = $2
`

func (q *Queries) GetMigrationRun(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, getMigrationRun, companyID, iD)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.RunNumber,
		&i.Status,
		&i.BandRoomID,
		&i.SourceCommitSha,
		&i.TargetBranch,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNextRunNumber = `-- name: GetNextRunNumber :one
SELECT COALESCE(MAX(run_number), 0) + 1 as next_number
FROM migration_runs
WHERE company_id = $1 AND project_id = $2
`

func (q *Queries) GetNextRunNumber(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextRunNumber, companyID, projectID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const listMigrationRuns = `-- name: ListMigrationRuns :many
SELECT id, company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, error_message, started_at, completed_at, created_by, created_at, updated_at FROM migration_runs
WHERE company_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

func (q *Queries) ListMigrationRuns(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID, limit int32, offset int32) ([]MigrationRun, error) {
	rows, err := q.db.Query(ctx, listMigrationRuns,
		companyID,
		projectID,
		limit,
		offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigrationRun{}
	for rows.Next() {
		var i MigrationRun
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ProjectID,
			&i.RunNumber,
			&i.Status,
			&i.BandRoomID,
			&i.SourceCommitSha,
			&i.TargetBranch,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startMigrationRun = `-- name: StartMigrationRun :one
UPDATE migration_runs
SET status = $3, started_at = NOW()
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, error_message, started_at, completed_at, created_by, created_at, updated_at
`

func (q *Queries) StartMigrationRun(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, status *MigrationStatus) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, startMigrationRun, companyID, iD, status)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.RunNumber,
		&i.Status,
		&i.BandRoomID,
		&i.SourceCommitSha,
		&i.TargetBranch,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMigrationRunStatus = `-- name: UpdateMigrationRunStatus :one
UPDATE migration_runs
SET status = $3, error_message = $4
WHERE company_id = $1 AND id = $2
RETURNING id, company_id, project_id, run_number, status, band_room_id, source_commit_sha, target_branch, error_message, started_at, completed_at, created_by, created_at, updated_at
`

func (q *Queries) UpdateMigrationRunStatus(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, status *MigrationStatus, errorMessage *string) (MigrationRun, error) {
	row := q.db.QueryRow(ctx, updateMigrationRunStatus,
		companyID,
		iD,
		status,
		errorMessage,
	)
	var i MigrationRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ProjectID,
		&i.RunNumber,
		&i.Status,
		&i.BandRoomID,
		&i.SourceCommitSha,
		&i.TargetBranch,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
