// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ArtifactType string

const (
	ArtifactTypeTargetCode      ArtifactType = "target_code"
	ArtifactTypeTestCode        ArtifactType = "test_code"
	ArtifactTypeDbMigrationSql  ArtifactType = "db_migration_sql"
	ArtifactTypeDbRollbackSql   ArtifactType = "db_rollback_sql"
	ArtifactTypeDbValidationSql ArtifactType = "db_validation_sql"
	ArtifactTypeRiskReport      ArtifactType = "risk_report"
	ArtifactTypeMigrationReport ArtifactType = "migration_report"
	ArtifactTypePrDescription   ArtifactType = "pr_description"
)

func (e *ArtifactType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ArtifactType(s)
	case string:
		*e = ArtifactType(s)
	default:
		return fmt.Errorf("unsupported scan type for ArtifactType: %T", src)
	}
	return nil
}

type NullArtifactType struct {
	ArtifactType ArtifactType `json:"artifact_type"`
	Valid        bool         `json:"valid"` // Valid is true if ArtifactType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullArtifactType) Scan(value interface{}) error {
	if value == nil {
		ns.ArtifactType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ArtifactType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullArtifactType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ArtifactType), nil
}

type AuditAction string

const (
	AuditActionUserLogin           AuditAction = "user_login"
	AuditActionUserLogout          AuditAction = "user_logout"
	AuditActionUserInvited         AuditAction = "user_invited"
	AuditActionProjectCreated      AuditAction = "project_created"
	AuditActionFileUploaded        AuditAction = "file_uploaded"
	AuditActionMigrationRunCreated AuditAction = "migration_run_created"
	AuditActionBandRoomCreated     AuditAction = "band_room_created"
	AuditActionAgentMessageCreated AuditAction = "agent_message_created"
	AuditActionPrCreated           AuditAction = "pr_created"
	AuditActionArtifactDownloaded  AuditAction = "artifact_downloaded"
	AuditActionSettingsChanged     AuditAction = "settings_changed"
	AuditActionUserRoleChanged     AuditAction = "user_role_changed"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type DbMigrationRiskLevel string

const (
	DbMigrationRiskLevelLow      DbMigrationRiskLevel = "low"
	DbMigrationRiskLevelMedium   DbMigrationRiskLevel = "medium"
	DbMigrationRiskLevelHigh     DbMigrationRiskLevel = "high"
	DbMigrationRiskLevelCritical DbMigrationRiskLevel = "critical"
)

func (e *DbMigrationRiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DbMigrationRiskLevel(s)
	case string:
		*e = DbMigrationRiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for DbMigrationRiskLevel: %T", src)
	}
	return nil
}

type NullDbMigrationRiskLevel struct {
	DbMigrationRiskLevel DbMigrationRiskLevel `json:"db_migration_risk_level"`
	Valid                bool                 `json:"valid"` // Valid is true if DbMigrationRiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDbMigrationRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.DbMigrationRiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DbMigrationRiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDbMigrationRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DbMigrationRiskLevel), nil
}

type MembershipRole string

const (
	MembershipRoleOwner    MembershipRole = "owner"
	MembershipRoleAdmin    MembershipRole = "admin"
	MembershipRoleEngineer MembershipRole = "engineer"
	MembershipRoleReviewer MembershipRole = "reviewer"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type MessageType string

const (
	MessageTypeFinding         MessageType = "finding"
	MessageTypeTaskRequest     MessageType = "task_request"
	MessageTypeHandoff         MessageType = "handoff"
	MessageTypeReview          MessageType = "review"
	MessageTypeDecision        MessageType = "decision"
	MessageTypeArtifactCreated MessageType = "artifact_created"
	MessageTypeBlocker         MessageType = "blocker"
)

func (e *MessageType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageType(s)
	case string:
		*e = MessageType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageType: %T", src)
	}
	return nil
}

type NullMessageType struct {
	MessageType MessageType `json:"message_type"`
	Valid       bool        `json:"valid"` // Valid is true if MessageType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageType), nil
}

type MigrationPhase string

const (
	MigrationPhasePlanning     MigrationPhase = "planning"
	MigrationPhaseAnalysis     MigrationPhase = "analysis"
	MigrationPhaseTranslation  MigrationPhase = "translation"
	MigrationPhaseDbMigration  MigrationPhase = "db_migration"
	MigrationPhaseTesting      MigrationPhase = "testing"
	MigrationPhaseReview       MigrationPhase = "review"
	MigrationPhasePrGeneration MigrationPhase = "pr_generation"
	MigrationPhaseCompleted    MigrationPhase = "completed"
)

func (e *MigrationPhase) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MigrationPhase(s)
	case string:
		*e = MigrationPhase(s)
	default:
		return fmt.Errorf("unsupported scan type for MigrationPhase: %T", src)
	}
	return nil
}

type NullMigrationPhase struct {
	MigrationPhase MigrationPhase `json:"migration_phase"`
	Valid          bool           `json:"valid"` // Valid is true if MigrationPhase is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMigrationPhase) Scan(value interface{}) error {
	if value == nil {
		ns.MigrationPhase, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MigrationPhase.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMigrationPhase) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MigrationPhase), nil
}

type MigrationStatus string

const (
	MigrationStatusPending      MigrationStatus = "pending"
	MigrationStatusPlanning     MigrationStatus = "planning"
	MigrationStatusAnalyzing    MigrationStatus = "analyzing"
	MigrationStatusTranslating  MigrationStatus = "translating"
	MigrationStatusDbMigration  MigrationStatus = "db_migration"
	MigrationStatusTesting      MigrationStatus = "testing"
	MigrationStatusReviewing    MigrationStatus = "reviewing"
	MigrationStatusGeneratingPr MigrationStatus = "generating_pr"
	MigrationStatusCompleted    MigrationStatus = "completed"
	MigrationStatusFailed       MigrationStatus = "failed"
	MigrationStatusBlocked      MigrationStatus = "blocked"
	MigrationStatusNeedsRework  MigrationStatus = "needs_rework"
)

func (e *MigrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MigrationStatus(s)
	case string:
		*e = MigrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MigrationStatus: %T", src)
	}
	return nil
}

type NullMigrationStatus struct {
	MigrationStatus MigrationStatus `json:"migration_status"`
	Valid           bool            `json:"valid"` // Valid is true if MigrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMigrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MigrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MigrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMigrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MigrationStatus), nil
}

type ModelProvider string

const (
	ModelProviderIbm       ModelProvider = "ibm"
	ModelProviderOpenai    ModelProvider = "openai"
	ModelProviderAnthropic ModelProvider = "anthropic"
	ModelProviderGemini    ModelProvider = "gemini"
	ModelProviderDeepseek  ModelProvider = "deepseek"
)

func (e *ModelProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModelProvider(s)
	case string:
		*e = ModelProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for ModelProvider: %T", src)
	}
	return nil
}

type NullModelProvider struct {
	ModelProvider ModelProvider `json:"model_provider"`
	Valid         bool          `json:"valid"` // Valid is true if ModelProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModelProvider) Scan(value interface{}) error {
	if value == nil {
		ns.ModelProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModelProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModelProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModelProvider), nil
}

type PrStatus string

const (
	PrStatusOpen   PrStatus = "open"
	PrStatusMerged PrStatus = "merged"
	PrStatusClosed PrStatus = "closed"
	PrStatusDraft  PrStatus = "draft"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus `json:"pr_status"`
	Valid    bool     `json:"valid"` // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type SourceLanguage string

const (
	SourceLanguageCobol SourceLanguage = "cobol"
	SourceLanguageJava  SourceLanguage = "java"
	SourceLanguagePhp   SourceLanguage = "php"
)

func (e *SourceLanguage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SourceLanguage(s)
	case string:
		*e = SourceLanguage(s)
	default:
		return fmt.Errorf("unsupported scan type for SourceLanguage: %T", src)
	}
	return nil
}

type NullSourceLanguage struct {
	SourceLanguage SourceLanguage `json:"source_language"`
	Valid          bool           `json:"valid"` // Valid is true if SourceLanguage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSourceLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.SourceLanguage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SourceLanguage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSourceLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SourceLanguage), nil
}

type TargetLanguage string

const (
	TargetLanguageGo   TargetLanguage = "go"
	TargetLanguageRust TargetLanguage = "rust"
)

func (e *TargetLanguage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TargetLanguage(s)
	case string:
		*e = TargetLanguage(s)
	default:
		return fmt.Errorf("unsupported scan type for TargetLanguage: %T", src)
	}
	return nil
}

type NullTargetLanguage struct {
	TargetLanguage TargetLanguage `json:"target_language"`
	Valid          bool           `json:"valid"` // Valid is true if TargetLanguage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTargetLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.TargetLanguage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TargetLanguage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTargetLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TargetLanguage), nil
}

type TaskStatus string

const (
	TaskStatusPending    TaskStatus = "pending"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusCompleted  TaskStatus = "completed"
	TaskStatusFailed     TaskStatus = "failed"
	TaskStatusBlocked    TaskStatus = "blocked"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type AgentMessage struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	MigrationRunID uuid.UUID          `json:"migration_run_id"`
	BandRoomID     string             `json:"band_room_id"`
	BandMessageID  *string            `json:"band_message_id"`
	AgentName      string             `json:"agent_name"`
	MessageType    MessageType        `json:"message_type"`
	Phase          MigrationPhase     `json:"phase"`
	Summary        string             `json:"summary"`
	Payload        []byte             `json:"payload"`
	Confidence     pgtype.Numeric     `json:"confidence"`
	RequiresAction *bool              `json:"requires_action"`
	TargetAgent    *string            `json:"target_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AgentTask struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	MigrationRunID uuid.UUID          `json:"migration_run_id"`
	AgentName      string             `json:"agent_name"`
	TaskType       string             `json:"task_type"`
	Status         *TaskStatus        `json:"status"`
	InputData      []byte             `json:"input_data"`
	OutputData     []byte             `json:"output_data"`
	ErrorMessage   *string            `json:"error_message"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       AuditAction        `json:"action"`
	ResourceType *string            `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Details      []byte             `json:"details"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    *string            `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BandAgentRegistration struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    uuid.UUID          `json:"company_id"`
	BandRoomID   string             `json:"band_room_id"`
	AgentName    string             `json:"agent_name"`
	AgentRole    *string            `json:"agent_role"`
	Capabilities []byte             `json:"capabilities"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	LastActiveAt pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BandContextSnapshot struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	MigrationRunID uuid.UUID          `json:"migration_run_id"`
	BandRoomID     string             `json:"band_room_id"`
	SnapshotData   json.RawMessage    `json:"snapshot_data"`
	SnapshotAt     pgtype.Timestamptz `json:"snapshot_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type BandRoom struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	MigrationRunID  uuid.UUID          `json:"migration_run_id"`
	BandRoomID      string             `json:"band_room_id"`
	RoomName        string             `json:"room_name"`
	RoomDescription *string            `json:"room_description"`
	RoomMetadata    []byte             `json:"room_metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Company struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	SubscriptionTier *string            `json:"subscription_tier"`
	MaxProjects      *int32             `json:"max_projects"`
	MaxUsers         *int32             `json:"max_users"`
	Settings         []byte             `json:"settings"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type DbMigrationPlan struct {
	ID                       uuid.UUID             `json:"id"`
	CompanyID                uuid.UUID             `json:"company_id"`
	ProjectID                uuid.UUID             `json:"project_id"`
	MigrationRunID           uuid.UUID             `json:"migration_run_id"`
	SourceSchema             string                `json:"source_schema"`
	TargetSchema             string                `json:"target_schema"`
	MigrationSql             string                `json:"migration_sql"`
	RollbackSql              string                `json:"rollback_sql"`
	ValidationSql            *string               `json:"validation_sql"`
	RiskLevel                *DbMigrationRiskLevel `json:"risk_level"`
	RiskFactors              []byte                `json:"risk_factors"`
	EstimatedDurationSeconds *int32                `json:"estimated_duration_seconds"`
	RequiresDowntime         *bool                 `json:"requires_downtime"`
	ApprovedBy               pgtype.UUID           `json:"approved_by"`
	ApprovedAt               pgtype.Timestamptz    `json:"approved_at"`
	CreatedAt                pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz    `json:"updated_at"`
}

type GeneratedArtifact struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	MigrationRunID uuid.UUID          `json:"migration_run_id"`
	ArtifactType   ArtifactType       `json:"artifact_type"`
	FilePath       string             `json:"file_path"`
	FileName       string             `json:"file_name"`
	FileSize       int64              `json:"file_size"`
	StorageKey     string             `json:"storage_key"`
	Checksum       *string            `json:"checksum"`
	Metadata       []byte             `json:"metadata"`
	GeneratedBy    *string            `json:"generated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Membership struct {
	ID         uuid.UUID          `json:"id"`
	CompanyID  uuid.UUID          `json:"company_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Role       MembershipRole     `json:"role"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	InvitedAt  pgtype.Timestamptz `json:"invited_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MigrationRun struct {
	ID              uuid.UUID          `json:"id"`
	CompanyID       uuid.UUID          `json:"company_id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	RunNumber       int32              `json:"run_number"`
	Status          *MigrationStatus   `json:"status"`
	BandRoomID      *string            `json:"band_room_id"`
	SourceCommitSha *string            `json:"source_commit_sha"`
	TargetBranch    *string            `json:"target_branch"`
	ErrorMessage    *string            `json:"error_message"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ModelConfig struct {
	ID                 uuid.UUID          `json:"id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	Provider           ModelProvider      `json:"provider"`
	ModelName          string             `json:"model_name"`
	ApiEndpoint        *string            `json:"api_endpoint"`
	ApiKeyEncrypted    *string            `json:"api_key_encrypted"`
	DefaultTemperature pgtype.Numeric     `json:"default_temperature"`
	DefaultMaxTokens   *int32             `json:"default_max_tokens"`
	IsDefault          *bool              `json:"is_default"`
	Settings           []byte             `json:"settings"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Project struct {
	ID                 uuid.UUID          `json:"id"`
	CompanyID          uuid.UUID          `json:"company_id"`
	Name               string             `json:"name"`
	Description        *string            `json:"description"`
	SourceLanguage     SourceLanguage     `json:"source_language"`
	TargetLanguage     TargetLanguage     `json:"target_language"`
	EnableDbMigration  *bool              `json:"enable_db_migration"`
	GithubRepoUrl      *string            `json:"github_repo_url"`
	GithubPatEncrypted *string            `json:"github_pat_encrypted"`
	Settings           []byte             `json:"settings"`
	CreatedBy          uuid.UUID          `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type PullRequest struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	MigrationRunID uuid.UUID          `json:"migration_run_id"`
	PrNumber       int32              `json:"pr_number"`
	PrUrl          string             `json:"pr_url"`
	Title          string             `json:"title"`
	Description    *string            `json:"description"`
	SourceBranch   string             `json:"source_branch"`
	TargetBranch   string             `json:"target_branch"`
	Status         *PrStatus          `json:"status"`
	MergedAt       pgtype.Timestamptz `json:"merged_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID            uuid.UUID          `json:"id"`
	CompanyID     uuid.UUID          `json:"company_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	GithubOwner   string             `json:"github_owner"`
	GithubRepo    string             `json:"github_repo"`
	DefaultBranch *string            `json:"default_branch"`
	PatEncrypted  *string            `json:"pat_encrypted"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type SourceFile struct {
	ID             uuid.UUID          `json:"id"`
	CompanyID      uuid.UUID          `json:"company_id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	MigrationRunID pgtype.UUID        `json:"migration_run_id"`
	FilePath       string             `json:"file_path"`
	FileName       string             `json:"file_name"`
	FileSize       int64              `json:"file_size"`
	MimeType       *string            `json:"mime_type"`
	StorageKey     string             `json:"storage_key"`
	Checksum       *string            `json:"checksum"`
	UploadedBy     uuid.UUID          `json:"uploaded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	FullName      string             `json:"full_name"`
	AvatarUrl     *string            `json:"avatar_url"`
	EmailVerified *bool              `json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	IsGuest       bool               `json:"is_guest"`
}
