// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
WHERE company_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjects(ctx context.Context, companyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (company_id, name, description, source_language, target_language, enable_db_migration, github_repo_url, github_pat_encrypted, settings, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, name, description, source_language, target_language, enable_db_migration, github_repo_url, github_pat_encrypted, settings, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) CreateProject(ctx context.Context, companyID uuid.UUID, name string, description *string, sourceLanguage SourceLanguage, targetLanguage TargetLanguage, enableDbMigration *bool, githubRepoUrl *string, githubPatEncrypted *string, settings []byte, createdBy uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		companyID,
		name,
		description,
		sourceLanguage,
		targetLanguage,
		enableDbMigration,
		githubRepoUrl,
		githubPatEncrypted,
		settings,
		createdBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.SourceLanguage,
		&i.TargetLanguage,
		&i.EnableDbMigration,
		&i.GithubRepoUrl,
		&i.GithubPatEncrypted,
		&i.Settings,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = NOW()
WHERE company_id = $1 AND id = $2
`

func (q *Queries) DeleteProject(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProject, companyID, iD)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, company_id, name, description, source_language, target_language, enable_db_migration, github_repo_url, github_pat_encrypted, settings, created_by, created_at, updated_at, deleted_at FROM projects
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
`

func (q *Queries) GetProject(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, companyID, iD)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.SourceLanguage,
		&i.TargetLanguage,
		&i.EnableDbMigration,
		&i.GithubRepoUrl,
		&i.GithubPatEncrypted,
		&i.Settings,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, company_id, name, description, source_language, target_language, enable_db_migration, github_repo_url, github_pat_encrypted, settings, created_by, created_at, updated_at, deleted_at FROM projects
WHERE company_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

func (q *Queries) ListProjects(ctx context.Context, companyID uuid.UUID, limit int32, offset int32) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, companyID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.SourceLanguage,
			&i.TargetLanguage,
			&i.EnableDbMigration,
			&i.GithubRepoUrl,
			&i.GithubPatEncrypted,
			&i.Settings,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $3, description = $4, settings = $5
WHERE company_id = $1 AND id = $2 AND deleted_at IS NULL
RETURNING id, company_id, name, description, source_language, target_language, enable_db_migration, github_repo_url, github_pat_encrypted, settings, created_by, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateProject(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, name string, description *string, settings []byte) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		companyID,
		iD,
		name,
		description,
		settings,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.SourceLanguage,
		&i.TargetLanguage,
		&i.EnableDbMigration,
		&i.GithubRepoUrl,
		&i.GithubPatEncrypted,
		&i.Settings,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
