// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) (Membership, error)
	CompleteMigrationRun(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, status *MigrationStatus) (MigrationRun, error)
	CountAgentMessages(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID) (int64, error)
	CountCompanyMembers(ctx context.Context, companyID uuid.UUID) (int64, error)
	CountMigrationRuns(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID) (int64, error)
	CountProjects(ctx context.Context, companyID uuid.UUID) (int64, error)
	CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) (AgentMessage, error)
	CreateAuditLog(ctx context.Context, companyID pgtype.UUID, userID pgtype.UUID, action AuditAction, resourceType *string, resourceID pgtype.UUID, details []byte, ipAddress *netip.Addr, userAgent *string) (AuditLog, error)
	CreateBandRoom(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID, bandRoomID string, roomName string, roomDescription *string, roomMetadata []byte) (BandRoom, error)
	CreateCompany(ctx context.Context, name string, slug string, subscriptionTier *string, maxProjects *int32, maxUsers *int32, settings []byte) (Company, error)
	CreateGuestUser(ctx context.Context, email string) (User, error)
	CreateMembership(ctx context.Context, companyID uuid.UUID, userID uuid.UUID, role MembershipRole, invitedBy pgtype.UUID, invitedAt pgtype.Timestamptz) (Membership, error)
	CreateMigrationRun(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID, runNumber int32, status *MigrationStatus, bandRoomID *string, sourceCommitSha *string, targetBranch *string, createdBy uuid.UUID) (MigrationRun, error)
	CreateProject(ctx context.Context, companyID uuid.UUID, name string, description *string, sourceLanguage SourceLanguage, targetLanguage TargetLanguage, enableDbMigration *bool, githubRepoUrl *string, githubPatEncrypted *string, settings []byte, createdBy uuid.UUID) (Project, error)
	CreateRefreshToken(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt pgtype.Timestamptz) (RefreshToken, error)
	CreateUser(ctx context.Context, email string, passwordHash string, fullName string, avatarUrl *string) (User, error)
	DeleteCompany(ctx context.Context, id uuid.UUID) error
	DeleteExpiredTokens(ctx context.Context) error
	DeleteMembership(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) error
	DeleteProject(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAgentMessage(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (AgentMessage, error)
	GetAgentTimeline(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID) ([]GetAgentTimelineRow, error)
	GetBandRoom(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (BandRoom, error)
	GetBandRoomByBandID(ctx context.Context, bandRoomID string) (BandRoom, error)
	GetBandRoomByRunID(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID) (BandRoom, error)
	GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error)
	GetCompanyBySlug(ctx context.Context, slug string) (Company, error)
	GetCompanyMembers(ctx context.Context, companyID uuid.UUID) ([]GetCompanyMembersRow, error)
	GetMembership(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) (Membership, error)
	GetMigrationRun(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (MigrationRun, error)
	GetNextRunNumber(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID) (int32, error)
	GetProject(ctx context.Context, companyID uuid.UUID, iD uuid.UUID) (Project, error)
	GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserMembershipsRow, error)
	HardDeleteUser(ctx context.Context, id uuid.UUID) error
	ListAgentMessages(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID, limit int32, offset int32) ([]AgentMessage, error)
	ListAgentMessagesByPhase(ctx context.Context, companyID uuid.UUID, migrationRunID uuid.UUID, phase MigrationPhase) ([]AgentMessage, error)
	ListAuditLogs(ctx context.Context, companyID pgtype.UUID, limit int32, offset int32) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, companyID pgtype.UUID, action AuditAction, limit int32, offset int32) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, companyID pgtype.UUID, resourceType *string, resourceID pgtype.UUID) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, companyID pgtype.UUID, userID pgtype.UUID, limit int32, offset int32) ([]AuditLog, error)
	ListCompanies(ctx context.Context, limit int32, offset int32) ([]Company, error)
	ListMigrationRuns(ctx context.Context, companyID uuid.UUID, projectID uuid.UUID, limit int32, offset int32) ([]MigrationRun, error)
	ListProjects(ctx context.Context, companyID uuid.UUID, limit int32, offset int32) ([]Project, error)
	RevokeAllUserTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	StartMigrationRun(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, status *MigrationStatus) (MigrationRun, error)
	UpdateBandRoomMetadata(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, roomMetadata []byte) (BandRoom, error)
	UpdateCompany(ctx context.Context, iD uuid.UUID, name string, settings []byte) (Company, error)
	UpdateMembershipRole(ctx context.Context, companyID uuid.UUID, userID uuid.UUID, role MembershipRole) (Membership, error)
	UpdateMigrationRunStatus(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, status *MigrationStatus, errorMessage *string) (MigrationRun, error)
	UpdateProject(ctx context.Context, companyID uuid.UUID, iD uuid.UUID, name string, description *string, settings []byte) (Project, error)
	UpdateUser(ctx context.Context, iD uuid.UUID, fullName string, avatarUrl *string) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, iD uuid.UUID, passwordHash string) error
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
